- insert:
    - id: dsh-brand-version
      name: '@local/dsh-brand-version'
- insert:
    - id: dsh-file-trace
      name: '@dsh-external/dsh-file-trace'
- insert:
    - id: dsh-profiles
      name: '@lhh010/dsh-profiles'
